In [1]:
import torch

In [2]:
#checking the tensor
#contoh tensro

a_tensor = torch.tensor(([1,2,3,4,5],
                        [3,4,5,6,7],
                        [21,312,424,54,54])) #tensor ini should have a dimension of (3,5)

print(a_tensor.shape)

#what if you acces the first one
print(a_tensor[0].shape)

torch.Size([3, 5])
torch.Size([5])


In [3]:
for id_x, x in enumerate(a_tensor):
    #see if it's 1D tensor
    print(f"id {id_x}, value:{x}")
    print(x.shape)
    hasil_perkalian = torch.dot(x,x)
    print(hasil_perkalian)

id 0, value:tensor([1, 2, 3, 4, 5])
torch.Size([5])
tensor(55)
id 1, value:tensor([3, 4, 5, 6, 7])
torch.Size([5])
tensor(135)
id 2, value:tensor([ 21, 312, 424,  54,  54])
torch.Size([5])
tensor(283393)


In [4]:
0.433 * 0.1385

0.0599705

In [5]:
a = torch.tensor([0.4300, 0.1500, 0.8900])
b = torch.tensor(0.1385)

print(a * b)

tensor([0.0596, 0.0208, 0.1233])


In [6]:

#contoh self attention with no weights
torch.manual_seed(123)

inputs = torch.tensor(
[[0.43, 0.15, 0.89], # Your (x^1)
[0.55, 0.87, 0.66], # journey (x^2)
[0.57, 0.85, 0.64], # starts (x^3)
[0.22, 0.58, 0.33], # with (x^4)
[0.77, 0.25, 0.10], # one (x^5)
[0.05, 0.80, 0.55]] # step (x^6)
)

print(inputs)

#get the attention vector
#jadikan contoh querynya elemen ke 2 dari input
query = inputs[1]
attention_weights_2 = torch.empty(inputs.shape[0])

for id_x, x in enumerate(inputs):
#get the attention weights of this specific input
    attention_weights_2[id_x] = torch.dot(query, x)


#menggunakan secara cepat saja
attention_weights_2_norm = torch.softmax(attention_weights_2, dim=0)
print(f"norm: {attention_weights_2_norm}")
print(f"total: {attention_weights_2_norm.sum()}")

#create the context vector for this specific query value:
context_vector_2 = torch.zeros(size=query.shape)

for id_x, x in enumerate(inputs):
#mengakalikan nilai weights  dengan nilai querynya
    context_vector_2 += attention_weights_2_norm[id_x] * x #this is element wise operation

print(context_vector_2) #adalah representatif dari perkalian antara suatu query tertentu dengan semua input lainnya
                    #dimana input lainnya merupakan weighted vector 


print(f"\n{'-' * 10} BREAK {'-' * 10}")
print("Menggunakan semua input : \n")

attention_scores_real = inputs @ inputs.T  #menghitung weightsnya (6,6)

print(f"\n att real: {attention_scores_real} \n")

normalized_attention_scores = torch.softmax(attention_scores_real, dim=-1)
print(f"\n att norm: {normalized_attention_scores} \n")

#menjadikan context_vector kembali
context_vector = normalized_attention_scores @ inputs #menjadi (6,3) kembali
print("context vector:")
print(context_vector)


tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])
norm: tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])
total: 1.0
tensor([0.4419, 0.6515, 0.5683])

---------- BREAK ----------
Menggunakan semua input : 


 att real: tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]]) 


 att norm: tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958,

In [7]:
print(f"\n\n {'-' * 10} BREAK {'-' * 10}\n\n")
print("Merancang menggunakan weight matrices (KVQ):")

x_2  = inputs[1]
d_in = inputs.shape[1]
d_out = 2

#create the weight matrices
W_q = torch.nn.Parameter(torch.rand(size=(d_in, d_out), requires_grad=False))
W_k = torch.nn.Parameter(torch.rand(size=(d_in, d_out), requires_grad=False))
W_v = torch.nn.Parameter(torch.rand(size=(d_in, d_out), requires_grad=False))

#contoh melakukan perkaliannya
query_2 = x_2 @ W_q
key_2 = x_2 @ W_k
value_2 = x_2 @ W_v

print(query_2)

    



 ---------- BREAK ----------


Merancang menggunakan weight matrices (KVQ):
tensor([0.4306, 1.4551], grad_fn=<SqueezeBackward4>)


In [8]:

test_tensors = torch.rand(size=(2,6,3))

batch, num_token, d_in  = test_tensors.shape

print(test_tensors)

brooo = test_tensors.transpose(1,2)
print(brooo.shape)
print(brooo)

tensor([[[0.3821, 0.6605, 0.8536],
         [0.5932, 0.6367, 0.9826],
         [0.2745, 0.6584, 0.2775],
         [0.8573, 0.8993, 0.0390],
         [0.9268, 0.7388, 0.7179],
         [0.7058, 0.9156, 0.4340]],

        [[0.0772, 0.3565, 0.1479],
         [0.5331, 0.4066, 0.2318],
         [0.4545, 0.9737, 0.4606],
         [0.5159, 0.4220, 0.5786],
         [0.9455, 0.8057, 0.6775],
         [0.6087, 0.6179, 0.6932]]])
torch.Size([2, 3, 6])
tensor([[[0.3821, 0.5932, 0.2745, 0.8573, 0.9268, 0.7058],
         [0.6605, 0.6367, 0.6584, 0.8993, 0.7388, 0.9156],
         [0.8536, 0.9826, 0.2775, 0.0390, 0.7179, 0.4340]],

        [[0.0772, 0.5331, 0.4545, 0.5159, 0.9455, 0.6087],
         [0.3565, 0.4066, 0.9737, 0.4220, 0.8057, 0.6179],
         [0.1479, 0.2318, 0.4606, 0.5786, 0.6775, 0.6932]]])


### Contoh penerapan mekanisme Attention
Akan ditampilkan 3 penerapan mekanisme atensi yang setiap versinya merupakan pengemabangan dari versi sebelumnya 
yang lebih lengkap
1. Self attention dengan weights manual
2. Self attention dengan trainanble weights dan linear layer
3. Causal attention with mask self attention dan dropout layer
4. Multihead attentioan 

In [9]:
import torch.nn as nn

#### 1. Self Attention with trainable weights

In [10]:
class Attention_Mechanism_V2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        """
        Impelemntasi self attention yang telah teroptimisasi
        menggunakan layer linear dibandingkan dengan menggunakan 
        native parameter yang berasal dari nn.toch.Param
        """
        
        #initiate the weights 
        self.W_q = nn.Linear(in_features=d_in, out_features=d_out, bias=qkv_bias)
        self.W_k = nn.Linear(in_features=d_in, out_features=d_out, bias=qkv_bias)
        self.W_v = nn.Linear(in_features=d_in, out_features=d_out, bias=qkv_bias)


    #terapkan mekanisme atensinuya
    def forward(self, x):
        #create the matrix Q, K, V
        query = self.W_q(x)
        keys = self.W_k(x)
        values = self.W_v(x)    

        #lakukan perhitungan terhadap attention score
        attention_score = query @ keys.T
        attention_weights = torch.softmax(
            input=(attention_score / keys.shape[-1] ** 0.5),
            dim=-1
        )

        #menghitung konteks vektornya
        context_vector = attention_weights @ values
        return context_vector

##### 2. Masked Attention 
Adalah tipe attention yang digunakan pada bagian decoder di arstitektur transformer. Suatu input yang bisa mengakses token pada inputnya dan input sebelumnya, dan tidak bisa mengakses token setelahnya. Yang token setelah input tersebut akan *dimask* menjadi
0.

In [11]:
class Masked_Attention(nn.Module):
    """Adalah pengembangan lanjut dari kelas attention sebelumnya,
        yang akan menambahkan fungsional
        1. Masked attention
        2. Dropout layer
        3. Dapat memrposes input dalam batch
    """

    def __init__(self, d_in, d_out, context_length,
                 dropout, kqv_bias = False):
        super().__init__()

        self.W_q = nn.Linear(in_features=d_in, out_features=d_out, bias=kqv_bias)
        self.W_k = nn.Linear(in_features=d_in, out_features=d_out, bias=kqv_bias)
        self.W_v = nn.Linear(in_features=d_in, out_features=d_out, bias=kqv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
            'mask',
            torch.triu(torch.ones(context_length, context_length), diagonal=1)
        )

    def forward(self, x):

        #prepare the data with batch
        b, num_tokens, d_out = x.shape
        query = self.W_q(x)
        keys = self.W_k(x)
        values = self.W_v(x)

        #calulcate the attention scores
        att_scores = query @ keys.transpose(1,2)
        att_scores.masked_fill_(
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf
        )

        #calculate the attention weights
        att_weights = torch.softmax(att_scores/ keys.shape[-1] ** 0.5, dim=-1)

        #do the dropout
        att_weights = self.dropout(att_weights)

        #context vector
        context_vector = att_weights @ values

        return context_vector


#### 3. Multihead Attention:
jenis attention yang menggunakan beberapa head untuk menangkap hubungan dari berbagai macam context

In [25]:
class Multihead_Attention_V2(nn.Module):
    def __init__(self, d_in, d_out, context_length, dropout,
                 num_heads, qkv_bias=False):
        super().__init__()

        #assert that
        assert(d_out % num_heads == 0), \
        'Pastikan jumlah heads adalah angka yang dapat dibagi dengan d_out'

        #menginisasi parameter
        self.d_in = d_in
        self.d_out = d_out
        self.num_heads = num_heads
        self.heads_dim = self.d_out // num_heads

        #the weights
        self.W_q = nn.Linear(in_features=d_in, out_features=d_out, bias = qkv_bias)
        self.W_k = nn.Linear(in_features=d_in, out_features=d_out, bias = qkv_bias)
        self.W_v = nn.Linear(in_features=d_in, out_features=d_out, bias = qkv_bias)
        self.out_proj = nn.Linear(d_out, d_out)
        self.dropout = nn.Dropout(dropout)

        #config
        self.register_buffer(
            'mask',
            torch.triu(torch.ones(context_length, context_length), diagonal = 1)
        )


    def forward(self, X):

        #1. pertama adalah tentukan dimensinya
        batch, num_tokens, d_in = X.shape

        #inisasikan QKV
        query = self.W_q(X)
        keys = self.W_k(X)
        values = self.W_v(X)


        #2,.ubah dimensinya sehingga dapat memiliki dimensi (batch, num_tokens, num_head, head_dim)
        query = query.view(batch, num_tokens, self.num_heads, self.heads_dim) 
        keys = keys.view(batch, num_tokens, self.num_heads, self.heads_dim) 
        values = values.view(batch, num_tokens, self.num_heads, self.heads_dim) 

        #kemudian transpose agar dapat diproses secara parallel untuk semua num_head nya (batch, num_heads, num_tokens, head_dim)
        query = query.transpose(1,2)
        keys = keys.transpose(1,2)
        vaues = values.transpose(1,2)


        #3. Hitung attention score nya
        att_score = query @ keys.transpose (2,3) #(num_tokens, head_dim) @ (head_dim, num_tokens)

        #4. Create the mask
        att_mask = self.mask.bool()[:num_token][:num_token] #buat mask dengan besar yang saama dengan token

        #5. Apply the mask
        att_score.masked_fill_(att_mask, -torch.inf)

        #6. Calculate the attention weights
        att_weights = torch.Softmax(
            att_score / keys.shape[-1] ** 0.5, dim=-1
        )

        #7. Do the dropout on the attetion weights
        att_weights = self.dropout(att_weights)

        #8. Calculate the context vector
        context_vector = (att_weights @ values).transpose(1,2) #ubah lagi menjadi (batch, num_tokens, num_head, head_dim)
        context_vector = context_vector.contiguous().view(
            batch, num_tokens, self.d_out
        )
        context_vector = self.out_proj(context_vector)

        return context_vector


In [ ]:
#mengete saja ygyg

inputs = torch.rand(size=(100,256))

inputs_2 = torch.stack([inputs,inputs], dim=0)
print(inputs_2.shape)

batch, num_tokens, d_in = inputs_2.shape

#masukkan ke multihead att
multihead = Multihead_Attention_V2(
    d_in=d_in, d_out=256, context_length=num_tokens, dropout=0.0,
    num_heads=4
)

context_vector = multihead(inputs_2)
print(context_vector)
print(context_vector.shape)




torch.Size([2, 100, 256])


RuntimeError: The size of tensor a (100) must match the size of tensor b (1024) at non-singleton dimension 3